# -*- coding: utf-8 -*-
{
    'name': 'Золотой мяч',
    'version': '12',
    'description': 'ODOO для клуба Золотой мяч',
    'author': 'Basik Dmitry',
    'category': 'Tools',
    'maintainer': 'Basik Dmitry',
    'depends': ['base'],
    'data': [
        'views/aboniment_type_view.xml',
        'views/aboniment_view.xml',
        'security/ir.model.access.csv',
        'views/bday_view.xml',
        'views/report_coachs_view.xml',
        'views/works_view.xml',
        'views/type_training_view.xml',
        'views/cort_number_view.xml',
        'views/client_view.xml',
        'views/coach_view.xml',
        'views/main_menu.xml',
    ],
    'image': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': True,
}